### ISSUE TITLE
请问实验4.4在编译Tensorflow的时候有什么报错么

### ISSUE THREAD

**Issue by dreamerliii** [SeanLi-OI/AI-Computing-System-Lab#1]
我之前遇到了cnrt.h cnml.h 和一个cxx的文件说找不到 我看是链接问题，就从别的地方复制过来，然后那块编译就通过了，但最后出现了这个报错，不知道您有没有遇到过，不胜感激。
ImportError: /root/.cache/bazel/_bazel_root/68ccc90f8bebac4259f0b9444c5180bf/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cnrtGetDeviceCount

**Comment by SeanLi-OI** [comment]
我应该没有遇到过，我不太知道您的cnrt.h，cnml.h等文件是从哪里来的，但在我的印象里是不会缺少这些文件的。
我个人猜想唯一的可能就是在bazel build之前没有source env.sh。
其实还有可能就是您缺少了一些实验步骤（[readme.txt](https://github.com/SeanLi-OI/AI-Computing-System-Lab/blob/main/Lab3/exp_4_4_custom_tensorflow_op_student/readme.txt)），不过我初步看起来跟cnrt.h等没有关系。

**Comment by dreamerliii** [comment]
请问您还记得编译的是cpu还是mlu的文件吗，我昨天又尝试了不修改直接编译的cpu版本，也是报错，mlu就可以，然后我有参考了您的修改，没调用xxxxmlu.h那个文件才成功，确实很神奇，是书上有错吗😂。再次感谢您的回复

**Comment by EzioZz** [comment]
实验手册上写着build_cpu.sh，然后readme上写着编译build_mlu.sh。
